/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTalentPoolRouteImport } from './routes/_app.talent-pool'
import { Route as AppMyApprovalsRouteImport } from './routes/_app.my-approvals'
import { Route as AppVacanciesIndexRouteImport } from './routes/_app.vacancies.index'
import { Route as AppRequisitionsIndexRouteImport } from './routes/_app.requisitions.index'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app.onboarding.index'
import { Route as AppOffersIndexRouteImport } from './routes/_app.offers.index'
import { Route as AppInterviewsIndexRouteImport } from './routes/_app.interviews.index'
import { Route as AppCandidatesIndexRouteImport } from './routes/_app.candidates.index'
import { Route as AppVacanciesIdRouteImport } from './routes/_app.vacancies.$id'
import { Route as AppRequisitionsIdRouteImport } from './routes/_app.requisitions.$id'
import { Route as AppOnboardingIdRouteImport } from './routes/_app.onboarding.$id'
import { Route as AppOffersIdRouteImport } from './routes/_app.offers.$id'
import { Route as AppInterviewsIdRouteImport } from './routes/_app.interviews.$id'
import { Route as AppEmployeesNewRouteImport } from './routes/_app.employees.new'
import { Route as AppCandidatesIdRouteImport } from './routes/_app.candidates.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTalentPoolRoute = AppTalentPoolRouteImport.update({
  id: '/talent-pool',
  path: '/talent-pool',
  getParentRoute: () => AppRoute,
} as any)
const AppMyApprovalsRoute = AppMyApprovalsRouteImport.update({
  id: '/my-approvals',
  path: '/my-approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppVacanciesIndexRoute = AppVacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsIndexRoute = AppRequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersIndexRoute = AppOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AppRoute,
} as any)
const AppVacanciesIdRoute = AppVacanciesIdRouteImport.update({
  id: '/vacancies/$id',
  path: '/vacancies/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsIdRoute = AppRequisitionsIdRouteImport.update({
  id: '/requisitions/$id',
  path: '/requisitions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingIdRoute = AppOnboardingIdRouteImport.update({
  id: '/onboarding/$id',
  path: '/onboarding/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersIdRoute = AppOffersIdRouteImport.update({
  id: '/offers/$id',
  path: '/offers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIdRoute = AppInterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesNewRoute = AppEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-approvals': typeof AppMyApprovalsRoute
  '/talent-pool': typeof AppTalentPoolRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/employees/new': typeof AppEmployeesNewRoute
  '/interviews/$id': typeof AppInterviewsIdRoute
  '/offers/$id': typeof AppOffersIdRoute
  '/onboarding/$id': typeof AppOnboardingIdRoute
  '/requisitions/$id': typeof AppRequisitionsIdRoute
  '/vacancies/$id': typeof AppVacanciesIdRoute
  '/candidates/': typeof AppCandidatesIndexRoute
  '/interviews/': typeof AppInterviewsIndexRoute
  '/offers/': typeof AppOffersIndexRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
  '/requisitions/': typeof AppRequisitionsIndexRoute
  '/vacancies/': typeof AppVacanciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-approvals': typeof AppMyApprovalsRoute
  '/talent-pool': typeof AppTalentPoolRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/employees/new': typeof AppEmployeesNewRoute
  '/interviews/$id': typeof AppInterviewsIdRoute
  '/offers/$id': typeof AppOffersIdRoute
  '/onboarding/$id': typeof AppOnboardingIdRoute
  '/requisitions/$id': typeof AppRequisitionsIdRoute
  '/vacancies/$id': typeof AppVacanciesIdRoute
  '/candidates': typeof AppCandidatesIndexRoute
  '/interviews': typeof AppInterviewsIndexRoute
  '/offers': typeof AppOffersIndexRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/requisitions': typeof AppRequisitionsIndexRoute
  '/vacancies': typeof AppVacanciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/my-approvals': typeof AppMyApprovalsRoute
  '/_app/talent-pool': typeof AppTalentPoolRoute
  '/_app/candidates/$id': typeof AppCandidatesIdRoute
  '/_app/employees/new': typeof AppEmployeesNewRoute
  '/_app/interviews/$id': typeof AppInterviewsIdRoute
  '/_app/offers/$id': typeof AppOffersIdRoute
  '/_app/onboarding/$id': typeof AppOnboardingIdRoute
  '/_app/requisitions/$id': typeof AppRequisitionsIdRoute
  '/_app/vacancies/$id': typeof AppVacanciesIdRoute
  '/_app/candidates/': typeof AppCandidatesIndexRoute
  '/_app/interviews/': typeof AppInterviewsIndexRoute
  '/_app/offers/': typeof AppOffersIndexRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/requisitions/': typeof AppRequisitionsIndexRoute
  '/_app/vacancies/': typeof AppVacanciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-approvals'
    | '/talent-pool'
    | '/candidates/$id'
    | '/employees/new'
    | '/interviews/$id'
    | '/offers/$id'
    | '/onboarding/$id'
    | '/requisitions/$id'
    | '/vacancies/$id'
    | '/candidates/'
    | '/interviews/'
    | '/offers/'
    | '/onboarding/'
    | '/requisitions/'
    | '/vacancies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-approvals'
    | '/talent-pool'
    | '/candidates/$id'
    | '/employees/new'
    | '/interviews/$id'
    | '/offers/$id'
    | '/onboarding/$id'
    | '/requisitions/$id'
    | '/vacancies/$id'
    | '/candidates'
    | '/interviews'
    | '/offers'
    | '/onboarding'
    | '/requisitions'
    | '/vacancies'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/my-approvals'
    | '/_app/talent-pool'
    | '/_app/candidates/$id'
    | '/_app/employees/new'
    | '/_app/interviews/$id'
    | '/_app/offers/$id'
    | '/_app/onboarding/$id'
    | '/_app/requisitions/$id'
    | '/_app/vacancies/$id'
    | '/_app/candidates/'
    | '/_app/interviews/'
    | '/_app/offers/'
    | '/_app/onboarding/'
    | '/_app/requisitions/'
    | '/_app/vacancies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/talent-pool': {
      id: '/_app/talent-pool'
      path: '/talent-pool'
      fullPath: '/talent-pool'
      preLoaderRoute: typeof AppTalentPoolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-approvals': {
      id: '/_app/my-approvals'
      path: '/my-approvals'
      fullPath: '/my-approvals'
      preLoaderRoute: typeof AppMyApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vacancies/': {
      id: '/_app/vacancies/'
      path: '/vacancies'
      fullPath: '/vacancies/'
      preLoaderRoute: typeof AppVacanciesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requisitions/': {
      id: '/_app/requisitions/'
      path: '/requisitions'
      fullPath: '/requisitions/'
      preLoaderRoute: typeof AppRequisitionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers/': {
      id: '/_app/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof AppOffersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/': {
      id: '/_app/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/': {
      id: '/_app/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vacancies/$id': {
      id: '/_app/vacancies/$id'
      path: '/vacancies/$id'
      fullPath: '/vacancies/$id'
      preLoaderRoute: typeof AppVacanciesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requisitions/$id': {
      id: '/_app/requisitions/$id'
      path: '/requisitions/$id'
      fullPath: '/requisitions/$id'
      preLoaderRoute: typeof AppRequisitionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/$id': {
      id: '/_app/onboarding/$id'
      path: '/onboarding/$id'
      fullPath: '/onboarding/$id'
      preLoaderRoute: typeof AppOnboardingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers/$id': {
      id: '/_app/offers/$id'
      path: '/offers/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof AppOffersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/$id': {
      id: '/_app/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof AppInterviewsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/new': {
      id: '/_app/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AppEmployeesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/$id': {
      id: '/_app/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMyApprovalsRoute: typeof AppMyApprovalsRoute
  AppTalentPoolRoute: typeof AppTalentPoolRoute
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppEmployeesNewRoute: typeof AppEmployeesNewRoute
  AppInterviewsIdRoute: typeof AppInterviewsIdRoute
  AppOffersIdRoute: typeof AppOffersIdRoute
  AppOnboardingIdRoute: typeof AppOnboardingIdRoute
  AppRequisitionsIdRoute: typeof AppRequisitionsIdRoute
  AppVacanciesIdRoute: typeof AppVacanciesIdRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
  AppOffersIndexRoute: typeof AppOffersIndexRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
  AppRequisitionsIndexRoute: typeof AppRequisitionsIndexRoute
  AppVacanciesIndexRoute: typeof AppVacanciesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMyApprovalsRoute: AppMyApprovalsRoute,
  AppTalentPoolRoute: AppTalentPoolRoute,
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppEmployeesNewRoute: AppEmployeesNewRoute,
  AppInterviewsIdRoute: AppInterviewsIdRoute,
  AppOffersIdRoute: AppOffersIdRoute,
  AppOnboardingIdRoute: AppOnboardingIdRoute,
  AppRequisitionsIdRoute: AppRequisitionsIdRoute,
  AppVacanciesIdRoute: AppVacanciesIdRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
  AppOffersIndexRoute: AppOffersIndexRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
  AppRequisitionsIndexRoute: AppRequisitionsIndexRoute,
  AppVacanciesIndexRoute: AppVacanciesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
